MONGODB_SERVER = "localhost"   
MONGODB_PORT = 27017   
MONGODB_DB = "Sina"   
MONGODB_COLLECTION_INFOMATION = "Information"
MONGODB_COLLECTION_TWEETS = "Tweets"
MONGODB_COLLECTION_RELATIONSHIPS = "Relationships"
